---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: python:3
  commands:
    - make test-drone

- name: docker
  image: plugins/docker:latest
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: markis/otto
    tags: latest
  when:
    branch: master
