---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: lint
  depends_on: [clone]
  image: python:3.8-alpine
  commands:
    - export MAGICK_HOME=/usr
    - apk add --update git make
    - make lint
  volumes:
    - name: pc_cache
      path: /root/.cache/pre-commit
    - name: pip_cache
      path: /root/.cache/pip

- name: test
  depends_on: [clone]
  image: python:3-alpine
  commands:
    - export MAGICK_HOME=/usr
    - apk add --update build-base make imagemagick imagemagick-dev
    - make test-drone
  volumes:
    - name: pip_cache
      path: /root/.cache/pip

- name: publish
  depends_on: [lint, test]
  image: plugins/docker:latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: markis/otto
    tags: latest
    cache_from: markis/otto:latest
    storage_driver: overlay2
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    branch: [master]
    event: [push]

- name: deploy
  depends_on: [publish]
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: deploy_host
    username:
      from_secret: deploy_user
    password:
      from_secret: deploy_password
    script:
      - docker pull markis/otto:latest
      - docker service rm home_otto_job
      - docker service rm home_otto_discord
      - docker service rm home_otto_stream_posts
      - docker stack deploy --compose-file $HOME/docker-compose.yml home --with-registry-auth
  when:
    branch: [master]
    event: [push]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: pc_cache
    host:
      path: /data/drone/pc_cache/
  - name: pip_cache
    host:
      path: /data/drone/pip_cache/
