---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

steps:
- name: lint
  image: python:3.8
  commands:
    - make lint
  volumes:
    - name: pc_cache
      path: /root/.cache/pre-commit
    - name: pip_cache
      path: /root/.cache/pip

- name: test
  image: python:3.8
  commands:
    - make test-drone
  volumes:
    - name: pip_cache
      path: /root/.cache/pip

- name: publish
  image: plugins/docker:latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: markis/otto
    tags: latest
    cache_from: markis/otto:latest
    storage_driver: overlay2
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    branch: [master]
    event: [push]

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: deploy_host
    username:
      from_secret: deploy_user
    password:
      from_secret: deploy_password
    script:
      - echo hello
      - echo world
  when:
    branch: [master]
    event: [push]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: pc_cache
    host:
      path: /data/drone/pc_cache/
  - name: pip_cache
    host:
      path: /data/drone/pip_cache/
