repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v0.7.1
    hooks:
    -   id: check-ast
        language_version: python3
    -   id: check-case-conflict
        language_version: python3
    -   id: check-docstring-first
        language_version: python3
    -   id: debug-statements
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.900
    hooks:
    -   id: mypy
        language_version: python3
        args:
        - --strict
        - --ignore-missing-imports
        - --allow-untyped-decorators

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
        args:
        - --py37
        - --separate-from-import
        - --separate-relative

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        language_version: python3
        args:
        - otto/
        - tests/
