version: '3.9'

services:
  otto:
    image: markis/otto:latest
    container_name: otto
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - linux/amd64
    entrypoint: sleep infinity
    env_file:
      - .env
    volumes:
      - ./:/app
