version: "3.4"
services:
  app:
    container_name: app
    build:
      context: .
      target: otto_app
    restart: always
    volumes:
      - './:/otto'
    ports:
      - 5000:5000

  job:
    container_name: job
    build:
      context: .
      target: otto_job
    restart: always
    volumes:
      - './:/otto'
